version: '3.4'

services:
  php:
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/durchblicke/public
      - DATABASE_URL=postgres://postgresql:postgresql@pgsql:5432/durchblicke
    build:
      context: .
    volumes:
      - ./:/durchblicke
      # - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      durchblicke_network:
        ipv4_address: 10.200.1.2
  pgsql:
    build:
      context: ./.docker/pgsql/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    networks:
      durchblicke_network:
        ipv4_address: 10.200.1.3
networks:
  durchblicke_network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.200.1.0/24"
