version: '3.4'

services:
  app:
    ports:
      - 80:80
    environment:
      - APACHE_DOCUMENT_ROOT=/durchblicke/public
    build:
      context: .
    volumes:
      - ./:/durchblicke
      # - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf